Foolmoon
TitusWhang/EvolutionGame pull request #5
Opened 2023-10-23 02:58 UTC by TitusWhang

2023-11-01 22:44 UTC, mis825 requested changes
Would it be feasible to remove the purple lines that remain still for more than 10 seconds? Sometimes the purple lines permanently show on the screen without the Darwin.
![image](https://github.com/TitusWhang/EvolutionGame/assets/98486724/15c46663-4cdd-45fb-aa76-88565622b0c3)

2023-11-01 22:44 UTC, mis825 commented on Assets/Darwin/DarwinAI.cs
> -            dist = float.MaxValue;
Why is line 76 being removed?
`dist = float.MaxValue;`

2023-11-01 22:44 UTC, mis825 commented on Assets/Darwin/DarwinAI.cs
> -        if(traits.Energy <= 0)
Is `traits.Energy <= 0` the same as `!traits.isLiving()`?

2023-11-02 00:34 UTC, TitusWhang commented on Assets/Darwin/DarwinAI.cs
> -        if(traits.Energy <= 0)
Yes. This change is being made to use the `isLiving()` from DarwinTraits

2023-11-02 00:38 UTC, TitusWhang commented on Assets/Darwin/DarwinAI.cs
> -            dist = float.MaxValue;
I did `dist = float.MaxValue` to use `dist` as a comparison to all the distances between the current Darwin and every other object around it. If an object is closer than the previous object, set `dist` as the distance between the next object. However, I have found a better, efficient solution to keep track of all the objects that were around the current Darwin.

2023-11-02 00:39 UTC, TitusWhang commented
> Would it be feasible to remove the purple lines that remain still for more than 10 seconds? Sometimes the purple lines permanently show on the screen without the Darwin. ![image](https://user-images.githubusercontent.com/98486724/279818862-15c46663-4cdd-45fb-aa76-88565622b0c3.png)



> Would it be feasible to remove the purple lines that remain still for more than 10 seconds? Sometimes the purple lines permanently show on the screen without the Darwin. ![image](https://user-images.githubusercontent.com/98486724/279818862-15c46663-4cdd-45fb-aa76-88565622b0c3.png)

I haven't gotten to replicating that issue on my machine. I will try to fix it if I encounter it.

2023-11-02 22:24 UTC, mis825 approved these changes

2023-11-02 22:25 UTC, merged